# Generated by Django 2.0.5 on 2018-05-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='imdb_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='tmdb_id',
            field=models.IntegerField(null=True),
        ),
    ]
