# Generated by Django 2.0.5 on 2018-05-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180503_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='timestamp',
        ),
    ]
