# Generated by Django 2.0.5 on 2018-05-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20180503_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='timestamp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='timestamp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
