# Generated by Django 2.0.5 on 2018-05-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20180503_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie1', models.IntegerField()),
                ('movie2', models.IntegerField()),
                ('desviacion', models.FloatField()),
            ],
        ),
    ]
