# Generated by Django 2.0.5 on 2018-05-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_ratingcopy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingcopy',
            name='movie',
        ),
        migrations.DeleteModel(
            name='RatingCopy',
        ),
    ]
